config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('newsletter_app.urls', namespace='news')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter_app.apps import NewsletterAppConfig
from newsletter_app.views import (StartPageView, ClientView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView,
                                  NewsletterView, NewsletterCreateView, NewsletterDetailView, NewsletterUpdateView,
                                  NewsletterDeleteView, LogsView, change_newsletter_status)

app_name = NewsletterAppConfig.name

urlpatterns = [
    path('', cache_page(60)(StartPageView.as_view()), name='start_page'),
    path('index/', ClientView.as_view(), name='index'),
    path('new_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('newsletters/', NewsletterView.as_view(), name='newsletters'),
    path('newsletter/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletter/<int:pk>/update', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('newsletter/<int:pk>/delete', NewsletterDeleteView.as_view(), name='delete_newsletter'),
    path('logs/', LogsView.as_view(), name='logs'),
    path('newsletter_status/<int:pk>/', change_newsletter_status, name='newsletter_status'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import UserRegView, UserForgotPassView, GenerateNewPasswordView, verify_mail, toggle_activity, UserListView

app_name = 'users'
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('registration/', UserRegView.as_view(), name='reg'),
    path('verification_code/<str:code>', verify_mail, name='verification_code'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forgot_pass/', UserForgotPassView.as_view(), name='forgot_pass'),
    path('set_new_password/<uidb64>/<token>/', GenerateNewPasswordView.as_view(), name='set_new_password'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity')
]

newsletter_app/models.py
from django.db import models
from django.conf import settings
from datetime import date, timedelta


# Create your models here.
def get_date_now():
    """Получение текущей даты"""
    return date.today()


def get_date_plus_week():
    """Получение даты через неделю"""
    return date.today() + timedelta(weeks=1)


NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='Почта')
    full_name = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='Комментарий')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE,
                              verbose_name='Менеджер клиента')

    def __str__(self):
        return f'{self.full_name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема сообщения', blank=True)
    text = models.TextField(verbose_name='Текст сообщения', blank=True)
    newsletter = models.OneToOneField('Newsletter', on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'{self.subject}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Newsletter(models.Model):
    PERIODS_SEND = (
        ('DAILY', 'Раз в день'),
        ('WEEKLY', 'Раз в неделю'),
        ('MONTHLY', 'Раз в месяц'),
    )

    STATUSES_SEND = (
        ('CREATED', 'Создана'),
        ('STARTED', 'Запущена'),
        ('COMPLETED', 'Завершена'),
    )

    client = models.ManyToManyField(Client, verbose_name='Клиент')
    date_start = models.DateField(default=get_date_now, verbose_name='Дата старта рассылки')
    date_stop = models.DateField(default=get_date_plus_week, verbose_name='Дата завершение рассылки')
    period_send = models.CharField(max_length=20, choices=PERIODS_SEND, default='WEEKLY', verbose_name='Периодичность')
    status_send = models.CharField(max_length=20, choices=STATUSES_SEND, default='CREATED',
                                   verbose_name='Статус рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, **NULLABLE,
                              verbose_name='Менеджер клиента')

    def __str__(self):
        return f'Активна до {self.date_stop} - {self.period_send} - {self.status_send}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                'set_status_send',
                'Can change status_send'
            ),
        ]


class Logs(models.Model):
    time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки')
    status = models.CharField(max_length=10, verbose_name='Статус')
    mail_serv_response = models.TextField(verbose_name='Ответ почтового сервера')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    newsletter = models.ForeignKey(Newsletter, on_delete=models.CASCADE, verbose_name='Рассылка')

    def __str__(self):
        return f'Лог: {self.time}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

newsletter_app/forms.py
from django import forms
from django.forms import DateInput

from newsletter_app.models import Client, Newsletter, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            # if field_name != 'is_current' and field_name != 'is_published':
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        # fields = '__all__'
        exclude = ('owner',)


class NewsletterForm(StyleFormMixin, forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(NewsletterForm, self).__init__(*args, **kwargs)
        # Ограничиваем queryset для выбора клиентов только теми, которых создал текущий пользователь
        self.fields['client'].queryset = Client.objects.filter(owner=user)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    class Meta:
        model = Newsletter
        exclude = ('owner',)
        # widgets = {
        #     'date_start': DateInput(
        #         attrs={'type': 'date'}
        #     )
        # } коряво работает


class NewsletterFormModerator(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ('status_send',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

newsletter_app/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DetailView, DeleteView, TemplateView)
from newsletter_app.models import Client, Newsletter, Message
from newsletter_app.forms import ClientForm, NewsletterForm, MessageForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from newsletter_app.services import cache_it
from users.models import User
from random import shuffle


# Create your views here.
class StartPageView(LoginRequiredMixin, TemplateView):
    template_name = 'newsletter_app/start_page.html'

    def get_context_data(self, **kwargs):
        """Вывод информации на главную страницу"""
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'The NewsLetter Service'
        if not self.request.user.is_superuser:
            count_clients = len(Client.objects.filter(owner=self.request.user.pk))
            count_newsletters = len(Newsletter.objects.filter(owner=self.request.user.pk))
        else:
            count_clients = len(Client.objects.all())
            count_newsletters = len(Newsletter.objects.all())
        active_newsletters = len(Newsletter.objects.filter(owner=self.request.user.pk,
                                                           status_send='STARTED'))
        blog_items = cache_it()
        if blog_items:
            blog_list = [blog for blog in blog_items]
            shuffle(blog_list)
            random_blog_list = blog_list[:3]
            context_data['random_blog_list'] = random_blog_list
        context_data['count_clients'] = count_clients
        context_data['count_newsletters'] = count_newsletters
        context_data['active_newsletters'] = active_newsletters

        return context_data


class ClientView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    model = Client
    permission_required = ('newsletter_app.view_client',)

    def get_queryset(self, *args, **kwargs):
        """Переопределение модели и прав доступа для Модератора"""
        queryset = super().get_queryset()
        if self.request.user.groups.filter(name='Moderators'):
            self.model = User
            self.permission_required = ('users.set_is_active',)
            self.template_name = 'users/user_list.html'
        else:
            queryset = queryset.filter(owner=self.request.user)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        """Формирование object_list в зависимости от группы пользователя"""
        context_data = super().get_context_data(**kwargs)
        current_user = self.request.user
        context_data['title'] = 'Список клиентов'
        if self.request.user.groups.filter(name='Moderators'):
            context_data['object_list'] = User.objects.exclude(email=current_user)
            context_data['object_list'] = context_data['object_list'].exclude(is_superuser=True).order_by('email')
            context_data['title'] = 'Список пользователей'
        # context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список клиентов'
        count_clients = len(Client.objects.filter(owner=self.request.user.pk))
        count_newsletters = len(Newsletter.objects.filter(owner=self.request.user.pk))
        active_newsletters = len(Newsletter.objects.filter(owner=self.request.user.pk, status_send='STARTED'))
        context_data['count_clients'] = count_clients
        context_data['count_newsletters'] = count_newsletters
        context_data['active_newsletters'] = active_newsletters
        return context_data


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('news:index')
    permission_required = ('newsletter_app.add_client',)

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Редактирование клиента"""
    model = Client
    form_class = ClientForm
    permission_required = ('newsletter_app.change_client',)

    def get_success_url(self):
        return reverse_lazy('news:client', args=[self.object.pk])


class ClientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Client
    permission_required = ('newsletter_app.view_client',)
    extra_context = {'title': 'Просмотр клиента'}


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Удаление клиента"""
    model = Client
    success_url = reverse_lazy('news:index')
    permission_required = ('newsletter_app.delete_client',)

    def get_context_data(self, **kwargs):
        """
        Подтверждение удаления
        """
        context_data = super().get_context_data(**kwargs)
        client_item = Client.objects.get(pk=self.kwargs.get('pk'))
        context_data['client_pk'] = client_item.pk
        context_data['title'] = f'Удаление клиента {client_item}'
        return context_data


class NewsletterView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Просмотр рассылок"""
    model = Newsletter
    permission_required = ('newsletter_app.view_newsletter',)
    extra_context = {'title': 'Рассылки'}

    def get_queryset(self):
        queryset = super().get_queryset()
        if (not self.request.user.is_staff and not self.request.user.is_superuser
                and not self.request.user.groups.filter(name='Moderators')):
            queryset = queryset.filter(owner=self.request.user).order_by('owner')
        return queryset.order_by('owner')


class NewsletterCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """создание рассылки"""
    model = Newsletter
    form_class = NewsletterForm
    permission_required = ('newsletter_app.add_newsletter',)

    def get_success_url(self):
        return reverse_lazy('news:newsletter_detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(NewsletterCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user  # Передаю текущего пользователя в форму
        return kwargs


class NewsletterUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Редактирование рассылки"""
    model = Newsletter
    form_class = NewsletterForm
    permission_required = ('newsletter_app.change_newsletter',)

    def get_success_url(self):
        return reverse_lazy('news:newsletter_detail', args=[self.object.pk])

    def get_form_kwargs(self):
        kwargs = super(NewsletterUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user  # Передаем текущего пользователя в форму
        return kwargs

    def get_context_data(self, **kwargs):
        """Склеивание форм рассылок и сообщений"""
        context_data = super().get_context_data(**kwargs)
        options_formset = inlineformset_factory(Newsletter, Message, form=MessageForm, extra=1, max_num=1,
                                                validate_max=True)
        if self.request.method == 'POST':
            context_data['formset'] = options_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = options_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            print(formset.instance)
            formset.save()
        return super().form_valid(form)


@login_required
@permission_required(perm='newsletter_app.set_status_send', login_url='users:login')
def change_newsletter_status(request, pk):
    """
    Переключение статуса рассылки для Модератора
    """
    newsletter_item = get_object_or_404(Newsletter, pk=pk)
    if newsletter_item.status_send != 'COMPLETED':
        newsletter_item.status_send = 'COMPLETED'
    else:
        newsletter_item.status_send = 'CREATED'
    newsletter_item.save()
    return redirect(reverse('newsletter_app:newsletters'))


class NewsletterDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Newsletter
    extra_context = {'title': 'Детали рассылки'}
    permission_required = ('newsletter_app.view_newsletter',)


class NewsletterDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Newsletter
    success_url = reverse_lazy('news:newsletters')
    permission_required = ('newsletter_app.delete_newsletter',)

    def get_context_data(self, **kwargs):
        """
        Подтверждение удаления
        """
        context_data = super().get_context_data(**kwargs)
        newsletter_item = Newsletter.objects.get(pk=self.kwargs.get('pk'))
        context_data['newsletter_pk'] = newsletter_item.pk
        context_data['title'] = f'Удаление рассылки {newsletter_item}'
        return context_data


class LogsView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """Просмотр Логов"""
    model = Newsletter      # так проще:)
    extra_context = {'title': 'LoGs'}
    template_name = 'newsletter_app/logs_list.html'
    permission_required = 'newsletter_app.view_logs'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset

newsletter_app/templates/newsletter_app/client_detail.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ object.comment }}</h5>
                    <div class="card-footer">
                        <a class="btn btn-outline-warning mb-2" href="{% url 'news:update_client' object.pk %}">Редактировать</a>
                        <a class="btn btn-outline-danger float-right" href="{% url 'news:delete_client' object.pk %}">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h2 class="display-6 text-center mb-4">Рассылки</h2>

    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Тема</th>
                <th scope="col">Время отправки</th>
                <th scope="col">Периодичность</th>
                <th scope="col">Статус рассылки</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            {% for n in object.newsletter_set.all %}
            <tr>
                <td><a href="{% url 'news:newsletter_detail' n.pk %}">{{ n.message.subject }}</a></td>
                <td>{{ n.date_start }}</td>
                <td>{{ n.period_send }}</td>
                <td>{{ n.status_send }}</td>
            </tr>
            </tbody>
            {% endfor %}
        </table>
    </div>
</main>
{% endblock %}

newsletter_app/templates/newsletter_app/client_list.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<main>
    <a class="btn btn-outline-primary mb-5" href="{% url 'news:create_client' %}">Добавить клиента</a>
    {% if perms.newsletter_app.add_newsletter %}
    <a class="btn btn-outline-primary mb-5" href="{% url 'news:create_newsletter' %}">Создать рассылку</a>
    {% endif %}
    <a class="btn btn-outline-primary mb-5" href="https://chrome-dino.com/ru/">Dino</a>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ object.comment }}</h5>
                    <ul class="list-unstyled mt-3 mb-4">
                        {% for n in object.newsletter_set.all %}
                        <li>{{ n }}</li>
                        {% endfor %}
                    </ul>
                    <a class="btn btn-primary" href="{% url 'news:client' object.pk %}" role="button">Просмотр</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <h2 class="display-6 text-center mb-4">Что у нас есть:</h2>
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Количество рассылок всего</th>
                <th scope="col">Количество активных рассылок</th>
                <th scope="col">Количество клиентов</th>
            </tr>
            </thead>
            <tbody class="table-group-divider">
            <tr>
                <td>{{ count_newsletters }}</td>
                <td>{{ active_newsletters }}</td>
                <td>{{ count_clients }}</td>
            </tr>
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

newsletter_app/templates/newsletter_app/newsletter_detail.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<div class="row col-12">
    <div class="col-8">
        <div class="card mb-4 rounded-3 shadow-sm border-primary">
            <div class="card-header py-3 text-bg">
                <h5 class="card-title">Клиенты: </h5>
                {% for client in newsletter.client.all %}
                <h5 class="my-0 fw-normal">{{ client }}</h5>
                <hr>
                {% endfor %}
                <h4 class="card-title">Тема:</h4>
                <h4 class="my-0 fw-normal">{{ newsletter.message.subject }}</h4>
            </div>
            <div class="card-body">
                <h5 class="card-title">Текст рассылки:</h5>
                <h5 class="my-0 fw-normal">{{ newsletter.message.text }}</h5>
                <hr>
                <h5 class="card-title">Дата окончания:</h5>
                <h5 class="my-0 fw-normal">{{ newsletter.date_stop }}</h5>
                <hr>
                <h5 class="card-title">Периодичность - Статус:</h5>
                <h5 class="my-0 fw-normal">{{ newsletter.period_send }} - {{ newsletter.status_send }}</h5>
                <hr>
                {% if perms.newsletter_app.change_newsletter %}
                <a class="btn btn-primary" href="{% url 'news:update_newsletter' object.pk %}">Редактировать</a>
                {% endif %}
                {% if perms.newsletter_app.delete_newsletter %}
                <a class="btn btn-danger" href="{% url 'news:delete_newsletter' object.pk %}">Удалить</a>
                {% endif %}
                {% if perms.newsletter_app.set_status_send %}
                {% if newsletter.status_send != 'COMPLETED' %}
                    <a class="btn btn-warning" href="{% url 'news:newsletter_status' object.pk %}">Остановить</a>
                {% else %}
                    <a class="btn btn-warning" href="{% url 'news:newsletter_status' object.pk %}">Возобновить</a>
                {% endif %}
                {% endif %}
                <a class="btn btn-success" href="{% url 'news:newsletters' %}">Отмена</a>
            </div>
        </div>
    </div>
</div>
<h2 class="display-6 text-center mb-4">Логи</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Время отправки</th>
      <th scope="col">Тема рассылки</th>
      <th scope="col">Статус</th>
      <th scope="col">Ответ сервера</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
  {% for log in newsletter.logs_set.all %}
        <tr>
          <td>{{ log.time }}</td>
          <td><a href="#">{{ log.newsletter.message.subject }}</a></td>
          <td>{{ log.status }}</td>
          <td>{{ log.mail_serv_response }}</td>
        </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

newsletter_app/templates/newsletter_app/newsletter_list.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
{% if perms.newsletter_app.add_newsletter %}
<a class="btn btn-outline-primary mb-5" href="{% url 'news:create_newsletter' %}">Создать рассылку</a>
{% endif %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">Клиент</th>
        <th scope="col">Пользователь</th>
        <th scope="col">Тема</th>
        <th scope="col">Время отправки</th>
        <th scope="col">Периодичность</th>
        <th scope="col">Статус рассылки</th>
        {% if perms.newsletter_app.set_status_send %}
        <th scope="col">Остановить/Возобновить</th>
        {% endif %}
    </tr>
    </thead>
    <tbody class="table-group-divider">
    {% for newsletter in newsletter_list %}
    {% for client in newsletter.client.all %}
    <tr>
        <th scope="col">{{ client }}</th>
        {% endfor %}
        <th>{{ newsletter.owner }}</th>
        <td><a href="{% url 'news:newsletter_detail' newsletter.pk %}">{{ newsletter.message.subject }}</a></td>
        <td>{{ newsletter.date_start }}</td>
        <td>{{ newsletter.period_send }}</td>
        <td>{{ newsletter.status_send }}</td>
        {% if perms.newsletter_app.set_status_send %}
        {% if newsletter.status_send != 'COMPLETED' %}
        <th scope="row"><a href="{% url 'news:newsletter_status' newsletter.pk %}">Остановить</a></th>
        {% else %}
        <th scope="row"><a href="{% url 'news:newsletter_status' newsletter.pk %}">Возобновить</a></th>
        {% endif %}
        {% endif %}
    </tr>
    </tbody>
    {% endfor %}
</table>
{% endblock %}