config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('newsletter_app.urls', namespace='news')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter_app/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from newsletter_app.apps import NewsletterAppConfig
from newsletter_app.views import (StartPageView, ClientView, ClientCreateView, ClientUpdateView, ClientDetailView, ClientDeleteView,
                                  NewsletterView, NewsletterCreateView, NewsletterDetailView, NewsletterUpdateView,
                                  NewsletterDeleteView, LogsView, change_newsletter_status)

app_name = NewsletterAppConfig.name

urlpatterns = [
    path('', cache_page(60)(StartPageView.as_view()), name='start_page'),
    path('index/', ClientView.as_view(), name='index'),
    path('new_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('delete_client/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('newsletters/', NewsletterView.as_view(), name='newsletters'),
    path('newsletter/create/', NewsletterCreateView.as_view(), name='create_newsletter'),
    path('newsletter/<int:pk>/', NewsletterDetailView.as_view(), name='newsletter_detail'),
    path('newsletter/<int:pk>/update', NewsletterUpdateView.as_view(), name='update_newsletter'),
    path('newsletter/<int:pk>/delete', NewsletterDeleteView.as_view(), name='delete_newsletter'),
    path('logs/', LogsView.as_view(), name='logs'),
    path('newsletter_status/<int:pk>/', change_newsletter_status, name='newsletter_status'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import UserRegView, UserForgotPassView, GenerateNewPasswordView, verify_mail, toggle_activity, UserListView

app_name = 'users'
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('registration/', UserRegView.as_view(), name='reg'),
    path('verification_code/<str:code>', verify_mail, name='verification_code'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forgot_pass/', UserForgotPassView.as_view(), name='forgot_pass'),
    path('set_new_password/<uidb64>/<token>/', GenerateNewPasswordView.as_view(), name='set_new_password'),
    path('activity/<int:pk>', toggle_activity, name='toggle_activity')
]

users/models.py
from django.db import models
from newsletter_app.models import NULLABLE
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    username = None  # для деактивации главного поля авторизации
    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='Страна', **NULLABLE)
    is_active = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    verification_code = models.CharField(max_length=4, verbose_name='Код верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        permissions = [
            (
                'set_is_active',
                'Can change active_status'
            ),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from newsletter_app.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

users/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group, Permission
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, View, ListView
from newsletter_app.models import Newsletter, Client, Message, Logs
from users.models import User
from users.forms import UserRegisterForm
from django.urls import reverse_lazy, reverse
import random
from django.conf import settings
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from newsletter_app.services import mailing_util
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.contenttypes.models import ContentType


# Create your views here.
class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """
    Контроллер просмотра пользователей
    """
    model = User
    permission_required = ('users.view_user',)
    extra_context = {'title': 'Список пользователей'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = User.objects.filter(is_superuser=False).order_by('email')
        # context_data['object_list'] = User.objects.order_by('email')
        return context_data


class UserRegView(CreateView):
    """
    Контроллер регистрации пользователя
    """
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/reg.html'

    def form_valid(self, form):
        """
        Верификация почты по ссылке
        """
        new_user = form.save()
        code = ''.join(random.sample(population='0123456789abcdefghijklmnopqrstuvwxyz', k=4))
        new_user.verification_code = code
        mailing_util(
            subject='Верификация SkyNews',
            message=f'''Перейдите по ссылке для верификации: http://127.0.0.1:8000/users/verification_code/{code}
    и введите Логин и пароль''',
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


def verify_mail(request, code):
    """
    Контроллер верификации email
    """
    try:
        user = User.objects.get(verification_code=code)
        user.is_active = True
        user.is_verified = True

        user.save()
        messages.success(request, 'Ваш аккаунт активирован!')

        users_group = Group.objects.filter(name='Users')
        print(users_group)
        if users_group:
            users_group = Group.objects.get(name='Users')
            user.groups.add(users_group)
        else:
            users_group = Group(name='Users')
            users_group.save()
            newsletter_content_type = ContentType.objects.get_for_model(Newsletter)
            add_permission = Permission.objects.get(codename="add_newsletter", content_type=newsletter_content_type)
            view_permission = Permission.objects.get(codename="view_newsletter", content_type=newsletter_content_type)
            change_permission = Permission.objects.get(codename="change_newsletter",
                                                       content_type=newsletter_content_type)
            delete_permission = Permission.objects.get(codename="delete_newsletter",
                                                       content_type=newsletter_content_type)
            users_group.permissions.add(add_permission, view_permission, change_permission, delete_permission)

            message_content_type = ContentType.objects.get_for_model(Message)
            add_permission = Permission.objects.get(codename="add_message", content_type=message_content_type)
            view_permission = Permission.objects.get(codename="view_message", content_type=message_content_type)
            change_permission = Permission.objects.get(codename="change_message", content_type=message_content_type)
            delete_permission = Permission.objects.get(codename="delete_message", content_type=message_content_type)
            users_group.permissions.add(add_permission, view_permission, change_permission, delete_permission)

            client_content_type = ContentType.objects.get_for_model(Client)
            add_permission = Permission.objects.get(codename="add_client", content_type=client_content_type)
            view_permission = Permission.objects.get(codename="view_client", content_type=client_content_type)
            change_permission = Permission.objects.get(codename="change_client", content_type=client_content_type)
            delete_permission = Permission.objects.get(codename="delete_client", content_type=client_content_type)
            users_group.permissions.add(add_permission, view_permission, change_permission, delete_permission)

            logs_content_type = ContentType.objects.get_for_model(Logs)
            add_permission = Permission.objects.get(codename="add_logs", content_type=logs_content_type)
            view_permission = Permission.objects.get(codename="view_logs", content_type=logs_content_type)
            change_permission = Permission.objects.get(codename="change_logs", content_type=logs_content_type)
            delete_permission = Permission.objects.get(codename="delete_logs", content_type=logs_content_type)
            users_group.permissions.add(add_permission, view_permission, change_permission, delete_permission)

            users_group.save()
            user.groups.add(users_group)
            user.save()
            # создаю группу модераторов с правами
            moderators_group, created = Group.objects.get_or_create(name='Moderators')
            if created:
                # Создаем группу сразу с разрешениями, если она только что была создана
                permissions = Permission.objects.filter(
                    codename__in=['set_is_active', 'set_status_send', 'view_newsletter']
                )
                moderators_group.permissions.set(permissions)
            moderators_group.save()

    except (ValueError, User.DoesNotExist):
        user = None
        messages.warning(request, 'Неверный код верификации')
    return redirect(reverse('users:login'))


def is_moderator(user):
    return user.groups.filter(name='Moderators').exists() or user.is_superuser


@login_required
@user_passes_test(test_func=is_moderator, login_url='users:login')
def toggle_activity(request, pk):
    """
    Функция переключения статуса is_active
    """
    user_item = get_object_or_404(User, pk=pk)
    if user_item.is_active:
        user_item.is_active = False
    else:
        user_item.is_active = True
    user_item.save()
    return redirect(reverse('newsletter_app:index'))


class UserForgotPassView(SuccessMessageMixin, PasswordResetView):
    """
    Контроллер сброса забытого пароля
    """
    form_class = PasswordResetForm
    from_email = settings.EMAIL_HOST_USER
    template_name = 'users/user_password_reset.html'
    success_url = reverse_lazy('users:login')
    success_message = 'Письмо с инструкцией по восстановлению пароля отправлено Вам на почту'
    email_template_name = 'users/mail_password_reset.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Восстановление пароля'
        return context_data


class GenerateNewPasswordView(SuccessMessageMixin, View):
    """
    Контроллер генерирования нового пароля и отправки его на почту
    """

    def get(self, request, uidb64: str, token: str):
        user = self.get_user(uidb64)
        from django.contrib.auth.tokens import default_token_generator
        if not user or not default_token_generator.check_token(user, token):
            messages.warning(self.request, 'Ошибка идентификации пользователя, попробуйте ещё раз.')
        else:
            new_password = User.objects.make_random_password()
            user.set_password(new_password)
            user.save()
            mailing_util(
                subject='Восстановление пароля',
                message=f'Ваш новый пароль для авторизации: {new_password}',
                recipient_list=[user.email]
            )
            messages.success(request, 'Вам на почту отправлено письмо с новым паролем для вашего аккаунта')
        return redirect(reverse('users:login'))

    @staticmethod
    def get_user(uid_base64: str) -> User | None:
        try:
            from django.utils.http import urlsafe_base64_decode
            uid = urlsafe_base64_decode(uid_base64).decode()
            user_id = int(uid)
            user = User.objects.get(pk=user_id)
        except (ValueError, User.DoesNotExist):
            user = None
        return user

users/templates/users/login.html
{% extends 'newsletter_app/base.html' %}
{% block content %}

<main>
    <a class="btn btn-outline-primary mb-5" href="https://chrome-dino.com/ru/">Dino</a>
    {% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
            {{ message }}<br/>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Авторизация</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="m-2 btn btn-success">
                            Войти
                        </button>
                        <a href="{% url 'users:forgot_pass' %}">Пароль забыт?</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</main>
{% endblock %}

users/templates/users/mail_password_reset.html
{% autoescape off %}
    
    Вы получили это электронное письмо, потому что запросили сброс пароля для своей учетной записи пользователя на {{ site_name }}.

	Перейдите на следующую страницу и получите новый пароль:
	{% block reset_link %}
	    {{ protocol }}://{{ domain }}{% url 'users:set_new_password' uidb64=uid token=token %}
	{% endblock %}
	Ваше email для входа: {{ user.email }}

{% endautoescape %}

users/templates/users/reg.html
{% extends 'newsletter_app/base.html' %}
{% block content %}

<main>
    {% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
            {{ message }}<br/>
            {% endfor %}
        </div>
    {% endif %}
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Регистрация</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <h6>Для подтверждения регистрации проверте почту!</h6>
                        <button type="submit" class="btn btn-success">
                            Зарегистрироваться
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'news:index' %}">Отмена</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</main>
{% endblock %}

users/templates/users/user_form.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<main>
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Редактирование профиля</div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            Сохранить
                        </button>
                        <a class="btn btn-outline-warning" href="{% url 'catalog:main_index' %}">Отмена</a>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'users:new_pass' %}" class="btn btn-danger">Сгенерировать новый пароль</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</main>
{% endblock %}

users/templates/users/user_list.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        {% for object in object_list %}
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm border-primary">
                <div class="card-header py-3 text-bg-primary border-primary">
                    <h4 class="my-0 fw-normal">{{ object }}</h4>
                </div>
                <div class="card-body">
                    {% if object.is_active %}
                        <a href="{% url 'users:toggle_activity' object.pk %}">Деактивировать</a>
                    {% else %}
                        <a href="{% url 'users:toggle_activity' object.pk %}">Активировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

users/templates/users/user_password_reset.html
{% extends 'newsletter_app/base.html' %}
{% block content %}
<main>
    <div class="card mb-3 border-0 nth-shadow">
        <div class="card-body">
            <div class="card-title nth-card-title">
                <h4>Ведите email, который указывали при регистрации</h4>
            </div>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark mt-2">Восстановить пароль</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}